version: "3.7"
services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: volume
        source: letsencrypt
        target: /etc/letsencrypt
      - type: volume
        source: nginx-logs
        target: /var/log
  wheretogo:
    build: /srv/idkwheretogo/www
    expose:
      - "5000"
    volumes:
      - type: bind
        source: /srv/idkwheretogo/www
        target: /srv/idkwheretogo/www
      - type: volume
        source: wheretogo-logs
        target: /var/log
volumes:
  wheretogo-logs:
  letsencrypt:
  nginx-logs:
